# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test: &laravel
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        entrypoint: ''
        command: bash -c 'start-container ./artisan migrate && start-container'
        depends_on:
            pgsql:
                condition: service_healthy
            redis:
                condition: service_healthy
    worker:
        <<: *laravel
        entrypoint: 'start-container'
        command: ./artisan queue:work
        scale: 3

    pgsql:
        image: 'postgres:15'
        environment:
            PGPASSWORD: 'postgres'
            POSTGRES_DB: 'laravel'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
